linters:
  enable-all: true
  disable:
    - funlen
    - gochecknoglobals
    - lll
    - nlreturn
    - wsl

issues:
  # We want to use golint but we don't care about some of the things that it complains about
  exclude:
    # We have many exported functions without comments
    - "exported \\w+ (\\S*['.]*)([a-zA-Z'.*]*) should have comment or be unexported"
    # We block-scope variables in many places, making it impossible to outdent
    - "if block ends with a return statement, so drop this else and outdent its block"
    # TODO in comments is okay
    - "Line contains TODO/BUG/FIXME"

linters-settings:
  govet:
    # Checking for shadowed variables is experimental and disabled by default
    check-shadowing: true

  whitespace:
    # Enforce newlines (or comments) after every multi-line if statement
    multi-if: true
